#
# Reun Media Bun moon tasks
#
# See also `.moon/tasks/typescript.yml`
#

$schema: "../../cache/schemas/tasks.json"

tasks:
  test:
    command: "bun test"
    inputs:
      - "@group(sources)"
      - "@group(configs)"
      - "@group(tests)"

  dev:
    command: "bun dev"
