$schema: "https://moonrepo.dev/schemas/tasks.json"

tasks:
  format:
    command:
      - "$workspaceRoot/vendor/bin/php-cs-fixer"
      - "fix"
      - "."
      - "--config=$workspaceRoot/.php-cs-fixer.php"
    inputs:
      - "@group(sources)"
      - "@group(configs)"
      - "@group(tests)"
      - ".php-cs-fixer.php" # Invalidate task cache on config change

  lint:
    deps:
      - format
      - lint-composer-json
      - phpstan

  test:
    command: "vendor/bin/pest"
    inputs:
      - "@group(sources)"
      - "@group(configs)"
      - "@group(tests)"

  dev:
    command: "composer dev"

  lint-composer-json:
    script: >
      composer validate
      && cd $workspaceRoot
      && composer normalize $projectSource/composer.json
    inputs:
      - "composer.json"
      - "composer.lock"
    options:
      internal: true

  phpstan:
    command: "$workspaceRoot/vendor/bin/phpstan"
    inputs:
      - "@group(sources)"
      - "@group(configs)"
      - "phpstan.dist.neon" # Invalidate task cache on config change
    options:
      internal: true
