$schema: "../../cache/schemas/tasks.json"

tasks:
  format:
    command:
      - "$workspaceRoot/vendor/bin/php-cs-fixer"
      - "fix"
      - "."
      - "--config=$workspaceRoot/.php-cs-fixer.php"
    inputs:
      - "@group(sources)"
      - "@group(configs)"
      - "@group(tests)"
      - ".php-cs-fixer.php" # Invalidate task cache on config change

  lint:
    inputs:
      - "@group(sources)"
      - "@group(configs)"
      - "@group(tests)"
    deps:
      - format
      - lint-composer-json
      - phpstan
      - target: lint-package-json
        optional: true

  test:
    command: "vendor/bin/pest"
    inputs:
      - "@group(sources)"
      - "@group(configs)"
      - "@group(tests)"

  dev:
    command: "composer dev"

  phpstan:
    command: "$workspaceRoot/vendor/bin/phpstan"
    inputs:
      - "@group(sources)"
      - "@group(configs)"
      - "phpstan.dist.neon" # Invalidate task cache on config change
    options:
      internal: true
